In [1]:
import numpy as np

In [21]:
#1
vector = np.linspace(1, 10, 10, dtype=int)
print(vector)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
#2
matrix = np.zeros((3,3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#3
matrix = np.random.randint(1,11, size=(5,5))
print(matrix)

[[9 1 6]
 [1 6 8]
 [2 1 4]]


In [ ]:

#4
matrix = np.random.random((4,4))
print(matrix)

[[0.16003313 0.51533541 0.67518138 0.19866199]
 [0.21900111 0.68989783 0.79602854 0.59464332]
 [0.38570258 0.2890924  0.30016885 0.28227759]
 [0.30156929 0.71980886 0.81305349 0.28955554]]


In [ ]:
#5
vector = np.random.randint(1, 11, size=5)
vector_two = np.random.randint(1, 11, size=5)
product = np.dot(vector, vector_two)
print(vector + vector_two)
print(vector_two - vector)
print(vector_two * vector)
print(f'Scalar product of two vectors:\n{product}')


[ 9 14 11 11 11]
[ 5  2  3 -5 -3]
[14 48 28 24 28]
Scolar product of two vectors:142


In [ ]:
#6
vector = np.random.randint(1, 11, size=7)
vector_two = np.random.randint(1, 11, size=7)
product = np.dot(vector, vector_two)
print(f'Scalar product of two vectors:\n{product}')


Scalar product of two vectors:379


In [ ]:
#7
matrix = np.random.randint(1, 11, size=(2,2))
matrix_two = np.random.randint(1, 11, size=(2,3))
print(matrix, matrix_two, sep='\n\n\n')
product = np.dot(matrix, matrix_two)
print(f'Product of two matrix is:\n{product}')


[[5 5]
 [3 3]]


[[ 9  1  1]
 [ 7 10  1]]
Product of two matrix:[[80 55 10]
 [48 33  6]]


In [56]:
#8
matrix = np.random.randint(1, 11, size=(3,3))
inverted_matrix = np.linalg.inv(matrix)
print(f'Matrix is:\n{matrix}')
print(f'Inverted matrix is:\n{inverted_matrix}')

Matrix is:
[[ 5  7 10]
 [ 7  9  5]
 [ 2 10  1]]
Inverted matrix is:
[[-0.12202381  0.27678571 -0.16369048]
 [ 0.00892857 -0.04464286  0.13392857]
 [ 0.1547619  -0.10714286 -0.01190476]]


In [57]:
#9
matrix = np.random.randint(1,11, size=(4,4))
matrix_T = matrix.T
print(f'Matrix is:\n{matrix}')
print(f'T_Matrix is:\n{matrix_T}')

Matrix is:
[[ 9 10  4  4]
 [ 8  3  8  3]
 [ 8  1  3  8]
 [ 3  1  4  5]]
T_Matrix is:
[[ 9  8  8  3]
 [10  3  1  1]
 [ 4  8  3  4]
 [ 4  3  8  5]]


In [11]:
#10
matrix = np.random.randint(1,11, size=(3,4))
vector = np.random.randint(1, 11, size=4)
print("Matrix:\n", matrix)
print("Vector:", vector)


# x = matrix * vector
# print(f'Product of matrix and vector:\n{x}')


product = np.dot(matrix, vector)
print(f'Product of matrix and vector:{product}')

Matrix:
 [[ 1  7 10 10]
 [ 9  8  7  6]
 [ 5  4  4  9]]
Vector: [ 4  2  9 10]
Product of matrix and vector:[208 175 154]


In [19]:
#Just testing some code here.
a = np.matrix('0.1,2;3,4')
print(a)

c = np.matrix([[1/3, 2],[2, 3]])
print(c)

b = np.array([[1/3, 2],[2, 3]])
print(b)

[[0.1 2. ]
 [3.  4. ]]
[[0.33333333 2.        ]
 [2.         3.        ]]
[[0.33333333 2.        ]
 [2.         3.        ]]


In [4]:
#Just testing some code here.
vector = np.linspace(1, 10, 10, dtype=int)
vector = np.append(vector, 3)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10  3]


In [14]:
#Just testing some code here.
c = np.matrix([[1/3, 2, 4],[2, 3, 4],[2, 5, 6]])
c_iv = np.linalg.inv(c)
print(c_iv)
print(c*c_iv)
print(np.dot(c,c_iv))
print((c*c_iv) == np.dot(c,c_iv))

[[-0.27272727  1.09090909 -0.54545455]
 [-0.54545455 -0.81818182  0.90909091]
 [ 0.54545455  0.31818182 -0.40909091]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.11022302e-16 1.00000000e+00]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.11022302e-16 1.00000000e+00]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
#11

matrix = np.random.random((2,3))
vector = np.random.random(3)
print("Matrix:\n", matrix)
print("Vector:", vector)


# x = matrix * vector
# print(f'Product of matrix and vector:\n{x}')


product = np.dot(matrix, vector)
print(f'Product of matrix and vector:{product}')

Matrix:
 [[0.1753487  0.75671782 0.66658809]
 [0.88472612 0.70823139 0.04807946]]
Vector: [0.39384297 0.70858677 0.39400313]
Product of matrix and vector:
[[0.06905985 0.53620024 0.2626378 ]
 [0.34844316 0.50184339 0.01894346]]
Product of matrix and vector:[0.86789789 0.86923001]


In [8]:
#12
matrix = np.random.randint(1,11, size=(2,2))
sub_matrix = np.random.randint(1,11, size=(2,2))

product = matrix * sub_matrix
print(f'Product of two matrix is:{product}')

multiply = np.multiply(matrix, sub_matrix)
print(f'Product of two matrix via multiply method is:{multiply}')

Product of two matrix is:[[16 30]
 [40 24]]
Product of two matrix via multiply method is:[[16 30]
 [40 24]]


In [ ]:
#13
matrix = np.random.randint(1,11, size=(2,2))
sub_matrix = np.random.randint(1,11, size=(2,2))

product = np.dot(matrix, sub_matrix)
print(f'Scalar Product of two matrix is:{product}')

In [16]:
#14
sum_of_matrix_elements = (np.random.randint(1,101, size=(5,5))).sum
print(f'Sum of all MATRIX elements is:{sum_of_matrix_elements()}')

#14.1
sum_of_matrix_elements_new = (np.random.randint(1,101, size=(5,5))).sum()
print(f'Sum of all MATRIX elements is:{sum_of_matrix_elements_new}')

Sum of all MATRIX elements is:1318
Sum of all MATRIX elements is:1435


In [18]:
#15
matrix = np.random.randint(1,11, size=(4,4))
sub_matrix = np.random.randint(1,11, size=(4,4))
difference = np.subtract(matrix, sub_matrix)
print(f'The difference of two MATRIX is:{difference}')

#15.1
difference_2 = matrix - sub_matrix
print(f'The difference of two MATRIX is:{difference_2}')

difference_3 = sub_matrix - matrix
print(f'The difference of two MATRIX is:{difference_3}')

The difference of two MATRIX is:[[-2 -1  5 -7]
 [ 3  2  3  5]
 [-3  1  3 -6]
 [ 4  7 -2 -3]]
The difference of two MATRIX is:[[-2 -1  5 -7]
 [ 3  2  3  5]
 [-3  1  3 -6]
 [ 4  7 -2 -3]]
The difference of two MATRIX is:[[ 2  1 -5  7]
 [-3 -2 -3 -5]
 [ 3 -1 -3  6]
 [-4 -7  2  3]]


In [26]:
#16
matrix = np.random.random((3,3))
sums = np.sum(matrix, axis=1)
print(f'The sum is:\n{sums}')
vector = sums.reshape(-1, 1)
print(f'The Vector is:\n{vector}')

The sum is:
[0.83065934 1.48586736 1.3193847 ]
The Vector is:
[[0.83065934]
 [1.48586736]
 [1.3193847 ]]


In [39]:
#17
matrix = np.random.randint(1, 300, size=(3,4))
print(f'The matrix is:\n{matrix}')
squared_matrix = np.square(matrix)
print(f'The squared - matrix is:\n{squared_matrix}')

#17.1
squared = list(map(lambda x: x**2, matrix))
# print(squared)
new_matrix = np.array(squared)
print(f'The squared - matrix via map method is:\n{new_matrix}')


The matrix is:
[[152 102 229 193]
 [117  49 143  90]
 [ 92 123 113 268]]
The squared - matrix is:
[[23104 10404 52441 37249]
 [13689  2401 20449  8100]
 [ 8464 15129 12769 71824]]
The squared - matrix via map method is:
[[23104 10404 52441 37249]
 [13689  2401 20449  8100]
 [ 8464 15129 12769 71824]]


In [55]:
#18
vector = np.linspace(1,50, num=4, dtype=int)
print(f'The vector  is:\n{vector}')

#18.1
vector_square_roots = np.array(list(map(lambda x: x**(1/2), vector)))
print(f'Vector with square roots of numbers via map method is:\n{vector_square_roots}')

sqr_vector = np.sqrt(vector)
print(f'Vector with square roots of numbers is:\n{sqr_vector}')


The vector  is:
[ 1 17 33 50]
Vector with square roots of numbers via map method is:
[1.         4.12310563 5.74456265 7.07106781]
Vector with square roots of numbers is:
[1.         4.12310563 5.74456265 7.07106781]
